# This is a basic workflow that is manually triggered

name: Manual test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      env:
        description: 'environment to run on'
        default: 'dev'
        required: true
      baseUrl:
        description: 'base url'
        default: 'https://dev.mosip.net'
        required: true
      modules:
        description: 'modules to run'
        default: 'kernel'
        required: true
      testLevel:
        description: 'tests to run'
        default: 'smokeAndRegression'
        required: true
         
jobs:
  readVariable:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        echo "env ${{ github.event.inputs.env }}"
        echo "baseUrl ${{ github.event.inputs.baseUrl }}"
        echo "modules ${{ github.event.inputs.modules }}"
        echo "testLevel ${{ github.event.inputs.testLevel }}"
